// <auto-generated />
namespace UBOSCENS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class story_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(story_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201603121148265_story_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
