// <auto-generated />
namespace UBOSCENS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedVisualizerStatistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedVisualizerStatistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221618507_added Visualizer Statistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
